## Pandas ETL operation
-  create Data
-  Get Data
-  Data access through iloc and loc

In [1]:
from pandas import DataFrame, read_csv

# General syntax to import a library but no functions: 
##import (library) as (give the library a nickname/alias)
import matplotlib.pyplot as plt
import pandas as pd #this is how I usually import pandas
import sys #only needed to determine Python version number
import matplotlib #only needed to determine Matplotlib version number

# Enable inline plotting
%matplotlib inline

In [2]:
# version check
print('Python version ' + sys.version)
print('Pandas version ' + pd.__version__)
print('Matplotlib version ' + matplotlib.__version__)

Python version 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Pandas version 0.23.0
Matplotlib version 2.2.2

## Create Data

In [3]:
# The inital set of baby names and birth rates
names = ['Bob','Jessica','Mary','John','Mel']
births = [968, 155, 77, 578, 973]
# The inital set of baby names and birth rates
BabyDataSet = list(zip(names,births))
BabyDataSet

[('Bob', 968), ('Jessica', 155), ('Mary', 77), ('John', 578), ('Mel', 973)]

In [4]:
df = pd.DataFrame(data = BabyDataSet, columns=['Names', 'Births'])
df

     Names  Births
0      Bob     968
1  Jessica     155
2     Mary      77
3     John     578
4      Mel     973

In [10]:
# store the data in csv files
df.to_csv('D:/rough/births1880.csv',index=False,header=False)

# Get Data

In [5]:
#read csv files
Location = r'D:/rough/diabetes.csv'

df = pd.read_table(Location,sep=',')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
11,10,168,74,0,0,38.0,0.537,34,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
15,7,100,0,0,0,30.0,0.484,32,1
16,0,118,84,47,230,45.8,0.551,31,1
17,7,107,74,0,0,29.6,0.254,31,1
18,1,103,30,38,83,43.3,0.183,33,0
19,1,115,70,30,96,34.6,0.529,32,1
20,3,126,88,41,235,39.3,0.704,27,0
21,8,99,84,0,0,35.4,0.388,50,0
22,7,196,90,0,0,39.8,0.451,41,1
23,9,119,80,35,0,29.0,0.263,29,1
24,11,143,94,33,146,36.6,0.254,51,1
25,10,125,70,26,115,31.1,0.205,41,1
26,7,147,76,0,0,39.4,0.257,43,1
27,1,97,66,15,140,23.2,0.487,22,0
28,13,145,82,19,110,22.2,0.245,57,0
29,5,117,92,0,0,34.1,0.337,38,0
...,...,...,...,...,...,...,...,...,...
738,2,99,60,17,160,36.6,0.453,21,0
739,1,102,74,0,0,39.5,0.293,42,1
740,11,120,80,37,150,42.3,0.785,48,1
741,3,102,44,20,94,30.8,0.400,26,0
742,1,109,58,18,116,28.5,0.219,22,0
743,9,140,94,0,0,32.7,0.734,45,1
744,13,153,88,37,140,40.6,1.174,39,0
745,12,100,84,33,105,30.0,0.488,46,0
746,1,147,94,41,0,49.3,0.358,27,1
747,1,81,74,41,57,46.3,1.096,32,0
748,3,187,70,22,200,36.4,0.408,36,1
749,6,162,62,0,0,24.3,0.178,50,1
750,4,136,70,0,0,31.2,1.182,22,1
751,1,121,78,39,74,39.0,0.261,28,0
752,3,108,62,24,0,26.0,0.223,25,0
753,0,181,88,44,510,43.3,0.222,26,1
754,8,154,78,32,0,32.4,0.443,45,1
755,1,128,88,39,110,36.5,1.057,37,1
756,7,137,90,41,0,32.0,0.391,39,0
757,0,123,72,0,0,36.3,0.258,52,1
758,1,106,76,0,0,37.5,0.197,26,0
759,6,190,92,0,0,35.5,0.278,66,1
760,2,88,58,26,16,28.4,0.766,22,0
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [39]:
# reading text data
location1='D:/rough/audiology.txt'

data = pd.read_table(location1, header=None)
data

                                                     0
0    [p1,cochlear_unknown,[boneAbnormal,air(mild),a...
1    [p2,cochlear_unknown,[boneAbnormal,air(moderat...
2    [p3,mixed_cochlear_age_fixation,[age_gt_60,air...
3    [p4,mixed_cochlear_age_otitis_media,[age_gt_60...
4    [p5,cochlear_age,[age_gt_60,boneAbnormal,air(m...
5    [p6,cochlear_age,[age_gt_60,boneAbnormal,air(m...
6    [p7,cochlear_unknown,[boneAbnormal,air(mild),a...
7    [p8,cochlear_unknown,[boneAbnormal,air(mild),a...
8    [p9,cochlear_unknown,[boneAbnormal,air(severe)...
9    [p10,cochlear_age,[age_gt_60,boneAbnormal,air(...
10   [p11,cochlear_age,[age_gt_60,boneAbnormal,air(...
11   [p12,cochlear_age,[age_gt_60,boneAbnormal,air(...
12   [p13,cochlear_unknown,[boneAbnormal,air(severe...
13   [p14,normal_ear,[air(normal),ar_c(elevated),ar...
14   [p15,cochlear_age,[age_gt_60,boneAbnormal,air(...
15   [p16,cochlear_age,[age_gt_60,boneAbnormal,air(...
16   [p17,cochlear_poss_noise,[boneAbnormal,notch_a...
17   [p18,cochlear_poss_noise,[boneAbnormal,notch_a...
18   [p19,normal_ear,[air(normal),ar_c(normal),ar_u...
19   [p20,cochlear_unknown,[m_sn_2_3k,air(normal),a...
20   [p21,cochlear_age_and_noise,[age_gt_60,boneAbn...
21   [p22,cochlear_age_and_noise,[age_gt_60,boneAbn...
22   [p23,cochlear_poss_noise,[boneAbnormal,notch_4...
23   [p24,normal_ear,[air(normal),ar_c(normal),ar_u...
24   [p25,cochlear_unknown,[boneAbnormal,air(modera...
25   [p26,cochlear_unknown,[boneAbnormal,mod_sn_gt_...
26   [p27,cochlear_unknown,[boneAbnormal,m_sn_gt_2k...
27   [p28,cochlear_poss_noise,[boneAbnormal,s_sn_gt...
28   [p29,acoustic_neuroma,[boneAbnormal,air(mild),...
29   [p30,cochlear_unknown,[boneAbnormal,air(mild),...
..                                                 ...
170  [p171,cochlear_age,[history(dizziness),m_m_sn,...
171  [p172,cochlear_unknown,[notch_4k,mod_sn_gt_2k,...
172  [p173,cochlear_unknown,[bone(unmeasured),notch...
173  [p174,cochlear_unknown,[bone(unmeasured),histo...
174  [p175,cochlear_unknown,[bone(unmeasured),histo...
175  [p176,cochlear_poss_noise,[bone(unmeasured),m_...
176  [p177,mixed_cochlear_unk_discontinuity,[o_ar_c...
177  [p178,cochlear_age,[history(noise),m_s_sn_gt_3...
178  [p179,cochlear_age,[m_s_sn_gt_4k,history(noise...
179  [p180,cochlear_unknown,[bone(unmeasured),mod_s...
180  [p181,cochlear_unknown,[bone(unmeasured),m_sn_...
181  [p182,cochlear_unknown,[o_ar_c(elevated),o_ar_...
182  [p183,cochlear_unknown,[o_ar_c(elevated),o_ar_...
183  [p184,cochlear_age,[bone(unmeasured),age_gt_60...
184  [p185,cochlear_age,[bone(unmeasured),age_gt_60...
185  [p186,possible_menieres,[static(normal),bone(m...
186  [p187,cochlear_unknown,[m_m_sn_gt_500,speech(p...
187  [p188,cochlear_unknown,[bone(mild),m_m_sn_gt_1...
188  [p189,conductive_fixation,[speech(very_poor),a...
189  [p190,conductive_fixation,[speech(normal),airB...
190  [p191,normal_ear,[age_gt_60,air(normal),bone(n...
191  [p192,cochlear_age_and_noise,[notch_4k,history...
192  [p193,cochlear_age_and_noise,[notch_4k,history...
193  [p194,cochlear_age,[m_m_sn,bone(unmeasured),ag...
194  [p195,cochlear_age,[m_m_sn,bone(unmeasured),ag...
195  [p196,cochlear_age,[notch_4k,m_m_sn_gt_2k,bone...
196  [p197,mixed_cochlear_age_otitis_media,[o_ar_c(...
197  [p198,possible_brainstem_disorder,[m_sn_gt_2k,...
198  [p199,cochlear_age,[m_sn_gt_2k,bone(unmeasured...
199  [p200,cochlear_age,[m_sn_gt_2k,bone(unmeasured...

[200 rows x 1 columns]

## accessing column and rows

In [5]:
# using iloc
print(df.columns)
df.iloc[0:4,0:2]

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

   Pregnancies  Glucose
0            6      148
1            1       85
2            8      183
3            1       89

In [6]:
# using loc
df.loc[0:5,['Glucose','Pregnancies','Outcome']]

   Glucose  Pregnancies  Outcome
0      148            6        1
1       85            1        0
2      183            8        1
3       89            1        0
4      137            0        1
5      116            5        0

In [8]:
df[['Glucose','Pregnancies','Outcome']]

     Glucose  Pregnancies  Outcome
0        148            6        1
1         85            1        0
2        183            8        1
3         89            1        0
4        137            0        1
5        116            5        0
6         78            3        1
7        115           10        0
8        197            2        1
9        125            8        1
10       110            4        0
11       168           10        1
12       139           10        0
13       189            1        1
14       166            5        1
15       100            7        1
16       118            0        1
17       107            7        1
18       103            1        0
19       115            1        1
20       126            3        0
21        99            8        0
22       196            7        1
23       119            9        1
24       143           11        1
25       125           10        1
26       147            7        1
27        97            1        0
28       145           13        0
29       117            5        0
..       ...          ...      ...
738       99            2        0
739      102            1        1
740      120           11        1
741      102            3        0
742      109            1        0
743      140            9        1
744      153           13        0
745      100           12        0
746      147            1        1
747       81            1        0
748      187            3        1
749      162            6        1
750      136            4        1
751      121            1        0
752      108            3        0
753      181            0        1
754      154            8        1
755      128            1        1
756      137            7        0
757      123            0        1
758      106            1        0
759      190            6        1
760       88            2        0
761      170            9        1
762       89            9        0
763      101           10        0
764      122            2        0
765      121            5        0
766      126            1        1
767       93            1        0

[768 rows x 3 columns]

In [7]:
# selecting 5 rows for a column

df['Glucose'][:5]

0    148
1     85
2    183
3     89
4    137
Name: Glucose, dtype: int64